name: Java Make Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11' # Set to the desired Java version

    - name: Build with make
      run: cd Java&&make
    
    - name: Run Test
      run: |
        expected_output=$(cat <<EOF
        ## DAIDALUSj V-2.0.2-FormalATM-v2.7.5
        ## ... (expected output lines) ...
        Preferred Altitude Direction: down
        Recovery Information for Altitude Bands:
          Time to Recovery: NaN [s]
          Recovery Horizontal Distance: NaN [nmi]
          Recovery Vertical Distance: NaN [ft]
        EOF
        )
        actual_output=$(./Java/DaidalusExample)
        if [[ "$actual_output" == "$expected_output" ]]; then
          echo "Test passed: Output matches expected result"
        else
          echo "Test failed: Output does not match expected result"
          echo "Expected:"
          echo "$expected_output"
          echo "Actual:"
          echo "$actual_output"
          exit 1
        fi
